### ISSUE TITLE
live example page does not work

### ISSUE THREAD

**Issue by robertlevy** [ideo/catcorrjs#31]

**Comment by deanmalmgren** [comment]
thanks for reporting the problem, @robertlevy! it looks like google must have changed how you access CSVs from google docs because this shows up in the console:

```
XMLHttpRequest cannot load https://docs.google.com/spreadsheets/d/1769DXwfvu0CziTnWgmCie_M_R1JhKKq5F2PyMFeS-xw/pub?output=csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ideo.github.io' is therefore not allowed access.
```

I'll hopefully get this sorted out soon but wanted to drop this note in there in case someone else has bandwidth to address it before me.
